export const INITIAL_WAVE = 1;

export const BASE_WAVE_SCORE_STEP = 20;

export const INITIAL_GAME_SPEED_MULTIPLIER = 1;

export const GAME_SPEED_MULTIPLIER_STEP = 0.05;

export const MAX_GAME_SPEED_MULTIPLIER = 2;

export const GAME_SPEED_RAMP_WAVE_COUNT = Math.ceil(
  (MAX_GAME_SPEED_MULTIPLIER - INITIAL_GAME_SPEED_MULTIPLIER) /
    GAME_SPEED_MULTIPLIER_STEP
);

export const WAVE_SCORE_STEP_GROWTH = Math.round(
  BASE_WAVE_SCORE_STEP *
    (GAME_SPEED_MULTIPLIER_STEP / INITIAL_GAME_SPEED_MULTIPLIER)
);

export const MAX_WAVE_SCORE_STEP = Math.round(
  BASE_WAVE_SCORE_STEP *
    (MAX_GAME_SPEED_MULTIPLIER / INITIAL_GAME_SPEED_MULTIPLIER)
);
