import { GAME_SCALE, GAME_SPEED_MULTIPLIER } from '@/game/constants';

const SPACESHIP_BASE_SIZE = 10;

const SPACESHIP_BASE_INITIAL_POSITION = {
  x: 88,
  y: 88,
} as const;

const SPACESHIP_BASE_ROTATION_SPEED = 0.08;

const SPACESHIP_BASE_MOVEMENT_SPEED = 1;

export const SPACESHIP_SIZE = SPACESHIP_BASE_SIZE * GAME_SCALE;

export const SPACESHIP_BOUNDARY_RADIUS = SPACESHIP_SIZE;

export const SPACESHIP_INITIAL_POSITION = {
  x: SPACESHIP_BASE_INITIAL_POSITION.x * GAME_SCALE,
  y: SPACESHIP_BASE_INITIAL_POSITION.y * GAME_SCALE,
};

export const SPACESHIP_ROTATION_SPEED =
  SPACESHIP_BASE_ROTATION_SPEED * GAME_SPEED_MULTIPLIER;

export const SPACESHIP_MOVEMENT_SPEED =
  SPACESHIP_BASE_MOVEMENT_SPEED * GAME_SCALE * GAME_SPEED_MULTIPLIER;
