import {
  GAME_LAYOUT,
  GAME_SCALE,
  GAME_SPEED_MULTIPLIER,
} from '@/game/constants';

const SPACESHIP_BASE_SIZE = 10;

const SPACESHIP_BASE_ROTATION_SPEED = 0.08;

const SPACESHIP_BASE_MOVEMENT_SPEED = 1;

const SPACESHIP_BASE_ENGINE_OFFSET = 5.5;

export const SPACESHIP_SIZE = SPACESHIP_BASE_SIZE * GAME_SCALE;

export const SPACESHIP_BOUNDARY_RADIUS = SPACESHIP_SIZE;

export function getSpaceshipInitialPosition() {
  return {
    x: GAME_LAYOUT.Width / 2,
    y: GAME_LAYOUT.Height / 2,
  };
}

export const SPACESHIP_ROTATION_SPEED =
  SPACESHIP_BASE_ROTATION_SPEED * GAME_SPEED_MULTIPLIER;

export const SPACESHIP_MOVEMENT_SPEED =
  SPACESHIP_BASE_MOVEMENT_SPEED * GAME_SCALE * GAME_SPEED_MULTIPLIER;

export const SPACESHIP_ENGINE_OFFSET =
  SPACESHIP_BASE_ENGINE_OFFSET * GAME_SCALE;

export const SPACESHIP_FACING_COUNT = 16;

export const SPACESHIP_FLAME_ANIMATION_SPEED = 1 / 6;

export const SPACESHIP_PARTICLES_ANIMATION_SPEED = 1 / 6;
