import { GAME_LAYOUT, GAME_SCALE } from '@/game/constants';

const SPACESHIP_BASE_SIZE = 10;

export const SPACESHIP_TURN_INTERVAL_MS = 110;

export const SPACESHIP_BASE_MOVEMENT_SPEED = 0.65 * GAME_SCALE;

export const SPACESHIP_GRAVITY_VELOCITY_RETENTION_PER_TICK = 0.97;

const SPACESHIP_BASE_ENGINE_OFFSET = 5.5;

export const SPACESHIP_SIZE = SPACESHIP_BASE_SIZE * GAME_SCALE;

export const SPACESHIP_BOUNDARY_RADIUS = SPACESHIP_SIZE;

export function getSpaceshipInitialPosition() {
  return {
    x: GAME_LAYOUT.Width / 2,
    y: GAME_LAYOUT.Height / 2,
  };
}

export const SPACESHIP_ENGINE_OFFSET =
  SPACESHIP_BASE_ENGINE_OFFSET * GAME_SCALE;

export const SPACESHIP_FLAME_ANIMATION_SPEED = 1 / 6;

export const SPACESHIP_PARTICLES_ANIMATION_SPEED = 1 / 6;
